###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: strive-user
####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/gxf_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

###mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      #逻辑删除配置
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 从配置文件批量读取，服务器启动的时候，把这些值放进com.gxf.order.configuration.GuoXiaoProperties这个类里面，然后再放进容器里面
xixi:
  haha: "10010"



